### ISSUE TITLE
Deep Support for ReadOnly

### ISSUE THREAD

**Issue by trayburn** [HighwayFramework/Highway.Data#101]
Brainstorming

Shatter IDataContext further in order to provide deep and explicit support for Read Only database operations.  Specifically my thought was to introduce `bool IsReadOnly {get;}` to the full `IDataContext` in order to allow automatic support for `.AsNoTracking()` in our queries.

It should probably also be integrated into our Repo Factories.

I'm not certain, but perhaps we should support a `SetReadWrite()` to upgrade from one to another.

**Comment by jigneshjdesai** [comment]
Have you guys decided anything on this? I am in need for this feature in my project.

**Comment by trayburn** [comment]
I've got plans to include it in the release of Highway v7, which will also
be .NET Core capable.  For the record there is a fairly easy extension
method hack of creating an extension method on IDataContext which is named
AsReadOnlyQueryable() or the like, and in that extension method, cast
IDataContext back to the DbContext it wrappers, and do both .AsQueryable()
and .AsNoTracking().  If you need it right now, this would be my suggested
route.

Tim

Tim Rayburn
Principal Consultant, Improving Enterprises - Microsoft Integration MVP -
Cell 817 760 0002 - Blog http://TimRayburn.net - Tim@TimRayburn.net

**Comment by jigneshjdesai** [comment]
Great, so this will cover adding AsNoTracking. Our SQL Server database cluster is setup as AvailabilityGroup in SQL Server 2012 with one DB server as ReadOnly database. So along with AsNoTracking, I also wanted to direct my ReadOnly operation to that ReadOnly database, either by using ApplicationIntent = ReadOnly or by specifying the data source as that server in the connection string. Do you have any idea/suggestion on how should I be implementing that?

Thanks,
Jignesh

**Comment by DevlinLiles** [comment]
Just be careful, here be dragons. If the repository is not read only, but a query is then you introduce the potential for erroneously added a detached object to a relationship and creating a duplicate add. I would tend more towards a ReadOnly Repository that hides the unit of work, and a readonly unit of work that doesn't allow the save changes ( throws an error would be my preference ). Thoughts?

**Comment by trayburn** [comment]
Picking this up as we move closer to Highway 7 being a thing, I agree with Devlin's opinion but the different connection strings is an interesting conundrum part of the description from @jigneshjdesai .  This seems like a good place to use our Domain concept for EF6, but would require IDomain to expose an IsReadOnly option, and then use of a Query Injector structure (which we are already building for Highway 7 to support other initiatives).

Leaving this open, there is work to be done here definitely but we may split the pieces eventually.
