### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by erlis** [HighwayFramework/Highway.Data#109]
Hi, 

This is not an issue, just a question that I have. I've been reading about this project online and I was wondering if you guys keep working on it. If not why? Do you consider it done? 

Thanks for the great work!!

**Comment by trayburn** [comment]
Erlis,

Thanks for asking.  For Entity Framework v6 we are really happy with where the project is right now, so we haven't been focused on moving that forward, it seems capable of everything we feel it needs to do (though if you disagree, by all means ask).

For EF Core & .NET Core, we are just beginning the process of converting the project to a .NET Core capable assembly.  It will take a good but of work, and reorganizing how we've distributed it,  but the work will be done eventually.  We started looking at this before the `project.json` -> `csproj` change.  That meant a little bit of loss of momentum for us, but we would still like to get it done sometime soon now that tooling and process are settling out.

**Comment by erlis** [comment]
Hi Trayburn, 

Thanks for the reply. I'm really interesting in start using a similar approach in a project I'm working at the moment, then I found HighwayFramework and I've been considering seriously using it. In the project I'm working you can find the typical repository implementation, not exactly following the priciples Highway framework proposed, my main concern is that we have to DB types one is MongoDB and the other is a SQL Server but with the Repositories implemented using Entity Framework. For the later I can use this but I don't know if I'll be able to use Highway Framework for MongoDB. Do you think is possible ???

Regards, 
Erlis

**Comment by DevlinLiles** [comment]
Erlis,
Thanks for the dialog. Yes you can. All you would need to do is implement the IDataContext interface for Mongo ( fairly small and easy ) the rest of the framework is built around the abstractions, so you would be off the races. Any "Advanced" features would not work ( i.e. Sql Stored procedure invocation ) but the rest of the platform would function well.
