### ISSUE TITLE
Latest version of Highway.Data not supported in .Net 4.6.2 projects

### ISSUE THREAD

**Issue by maike9** [HighwayFramework/Highway.Data#118]
Migrated my solution/projects to .Net 4.6.2.  Tried to update Highway to latest verison and git the following error.   Same for Highway.Data.EntityFramework

Could not install package 'Highway.Data 7.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by trayburn** [comment]
Thank you for bringing this to our attention.  We've been quickly iterating on .NET Core/Standard support given the EntityFramework 6.3 support for .NET Standard 2.1, but we missed that .NET Framework (4.6+) does not support .NET Standard 2.1 at this time.  We will create a multiple distribution ASAP to solve this.

**Comment by trayburn** [comment]
Version 7.0.2 was just published and includes support for NET4.5 in addition to NETSTANDARD21
