### ISSUE TITLE
EF Migrations Should Just Work

### ISSUE THREAD

**Issue by trayburn** [HighwayFramework/Highway.Data#43]

**Comment by bluefindata** [comment]
Hey guys, thank you for your comments last year.

I have looked back over your solutions and I have it implemented just like you explained, but I am running into another issue. I am using EF 6, so I'm not sure if something has changed in EF that is causing the issue or not. As far as I recall, your solution worked for me last year, so I am not quite sure what would have changed if it did.

I was not able to find where you were setting the initialize in your solutions, but this is how I am setting it when the application starts:

Database.SetInitializer(new MigrateDatabaseToLatestVersion<SqlCompactContext, Configuration>());

When researching this problem, I came across a solution that suggested calling Database.Initialize() to force the initialization process, but this did not work for me. I called it by creating the AdvancedCommand below and calling it right after SetInitializer. Here is the link to that solution: http://stackoverflow.com/questions/15537185/migratedatabasetolatestversion-initializer-failing-to-create-database 

public class InitializeDatabase : AdvancedCommand
    {
        public InitializeDatabase()
        {
            ContextQuery = c => c.Database.Initialize(true);
        }
    }

Here are my context files:

Configuration:
    public class Configuration : DbMigrationsConfiguration<SqlCompactContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(SqlCompactContext context)
        {        }
    }

Db Context:
public class SqlCompactContext : DataContext
    {
        public SqlCompactContext()
            : base(@"Data Source=|DataDirectory|\MyLocalDb.sdf; Password=*******;Initial Catalog=MyLocalDb;Integrated Security=True", new MyMappings())
        {
            
        }
    }

Mappings:
public class MyMappings : IMappingConfiguration
    {
        public void ConfigureModelBuilder(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.AddFromAssembly(Assembly.GetExecutingAssembly());

            modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
        }
    }

**Comment by bluefindata** [comment]
I'm still not sure why my original solution would not work, but I forced the update by implementing it manually.

var cfg = new Configuration(); 
    cfg.TargetDatabase = 
       new DbConnectionInfo( 
          theConnectionString, 
          "provider" );

    DbMigrator dbMigrator = new DbMigrator( cfg );
    dbMigrator.Update();

Here's the link: http://stackoverflow.com/questions/17901215/entity-framework-code-first-migrations-production-wpf-application
