### ISSUE TITLE
Unit Testing Query Parameters

### ISSUE THREAD

**Issue by bluefindata** [HighwayFramework/Highway.Data#73]
I have not been able to find a way to unit test the parameters that are passed into queries. Is there a way to do this?

For example, when I test that a call is made to GetCustomerById(), I have to use the generic .ReceivedWithAnyArgs() method. Ideally, I would like to set customerId and verify that the parameter being passed is what I am expecting. 

I have also ran into a similar issue when two queries pass the same data type in a method. I can't verify that the second query is being called because the first query is being called with the same data type.

//Unit Test
_repository.ReceivedWithAnyArgs(1).Find(new GetCustomerById(customerId));

//Call being Unit Tested
_repository.Find(new GetCustomerById(customerId));

**Comment by DevlinLiles** [comment]
I normally will mock the context with a set of data the supplies both, and then use a real repository. That has been the way I have stepped around this in the past, but let me see if there is an easy way we can surface some more data.

**Comment by bluefindata** [comment]
Thanks for the reply Devlin. I don't quite follow, can you give an example?
