### ISSUE TITLE
Conflict with Newest Common.Logging.Core (3.1)

### ISSUE THREAD

**Issue by stack247** [HighwayFramework/Highway.Data#79]
Great framework!

It seems to have issue with latest Common.Loggging package. Attow, it's version 3.1. It's worth noting that my project is Azure Cloud Service. The error is thrown at runtime when the project (Azure Cloud Service) is run.

Downgrading Common.Logging package to 2.2 seems to solve the issue (plus manually changing to config file to load 2.2 version - NuGet doesn't do this automatically when uninstalling package)

This is the error message I get:

{"Could not load file or assembly 'Common.Logging.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e' or one of its dependencies. The system cannot find the file specified.":"Common.Logging.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e"}

=== Pre-bind state information ===
LOG: DisplayName = Common.Logging.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e
 (Fully-specified)
LOG: Appbase = file:///C:/project/csx/Debug/roles/project/approot
LOG: Initial PrivatePath = C:\project\csx\Debug\roles\project\approot
Calling assembly : Highway.Data.EntityFramework, Version=5.2.0.0, Culture=neutral, PublicKeyToken=fe803c9600455796.
======
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\project\csx\Debug\roles\project\approot\project.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 2.2.0.0 redirected to 3.1.0.0.
LOG: Post-policy reference: Common.Logging.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

Could not load file or assembly 'Common.Logging.Core, Version=2.2.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e' or one of its dependencies. The system cannot find the file specified.

**Comment by DevlinLiles** [comment]
I am looking at this right now, and expect to have a fix today.

**Comment by DevlinLiles** [comment]
I am moving our packages to a 3.2.0 common logging dependency.

**Comment by DevlinLiles** [comment]
landed in package 6.0.1
