### ISSUE TITLE
Before/After Scalar/Command are missing context

### ISSUE THREAD

**Issue by marcindzwonnik** [HighwayFramework/Highway.Data#85]
Hi,

As visible below, only before/after query events have a context of what query was executed. 
Scalar/Command events are missing it, this seems like pretty quick change, can it be added?

    public class BeforeQuery : EventArgs
    {
        public object Query { get; set; }

        public BeforeQuery(object query)
        {
            Query = query;
        }
    }

    public class BeforeCommand : EventArgs
    {
         
    }

**Comment by marcindzwonnik** [comment]
Created pull request 
https://github.com/HighwayFramework/Highway.Data/pull/87

**Comment by DevlinLiles** [comment]
Merged and Closed working on a push shortly
