### ISSUE TITLE
Support for Azure

### ISSUE THREAD

**Issue by vorosoft** [HighwayFramework/Highway.Data#91]
Hello, any chance of support for Azure Table Storage? Or can Highway.Data be made to work with Entity Framework 7? EF7 is pretty well developed now and I'd love to see Highway.Data supporting that as well as EF6.

Regards,
Richard

**Comment by trayburn** [comment]
EF 7 support is coming, we've just started our process of moving to CoreCLR and supporting EF Core.  In time it will arrive, we promise.
