### ISSUE TITLE
Entity Framework 7 Support

### ISSUE THREAD

**Issue by jkanczler** [HighwayFramework/Highway.Data#93]
Entity Framework 7 is coming. Do you have any plan to support it?

**Comment by trayburn** [comment]
EF Core support is coming, we've started the process of updating for our v7 release which will move to support CoreCLR, reorganize into some new NuGet packages, and support EF Core.

It should be said, EF Core is not at feature parity with EF 6, so this will not be a 1 for 1 replace for Highway.Data.EntityFramework and will be shipping as a new package, not the v7 of Highway.Data.EntityFramework

Initial work can be seen on `feature/efcore` branch, but it is super preliminary as of this writing.
